### PR TITLE
MTP40-F I2C test

### PR DESCRIPTION
**Pull request by M66B**

### CODE REVIEW

**Comment by M66B** [comment]
From the MTP40-F datasheet:

```
1.Send a start signal;
2.Send an address to write(slave address + R/W=0x64) and check responses;
3.Send a read command (0x03) and check the responses;
4.Send a stop signal;
5.Send a start signal;
6.Send an address to read (slave address + R/W(1) =0x65) and check responses;
7.Read 3 bytes from the module and send responses;
8.Send a stop signal.
```
Structure of response:

```
CO2 concentration = high byte of CO2 concentration*256 + low concentration byte
Data valid byte, 0x00 means data is valid, 0xFF means data is invalid.
```

**Comment by RobTillaart** [comment]
Thanks for the PR, will look into it later today.

**Comment by RobTillaart** [comment]
@M66B 
Merged your comment into master branch, will not make a new release for it.

Downloaded the MTP40-F datasheet as I only had the C and D version.
This (MTP40F) datasheet gives slightly better info about the I2C interface. (request 3 bytes instead of 7.

Could you give this a try?
It would be slightly faster as it uses less data.

```cpp
uint16_t readMTP40_F(uint8_t address)  //  address 0x32
{
  Wire.beginTransmission(address);
  //    Wire.write(0x52);
  if (Wire.endTransmission() != 0) return 0;

  if (Wire.requestFrom(address, 3) == 3)
  {
    uint16_t ppm = Wire.read() * 256;
    ppm += Wire.read();
    uint8_t status = Wire.read();
    if (status == 0xFF) Serial.println("Invalid PPM");
    return ppm;
  }
  return 0;
}
```

I look into ordering an MTP40_F for additional testing.
I assume that the 0x52 in the original demo code identifies a register, so it would be interesting to see if other "register addresses" provide additional data.


PS, you're from Netherlands? I live in Gemert.

**Comment by RobTillaart** [comment]
@M66B 

Q: did you test the TTL rs232 interface?
if so which library?
I am considering a new library for the F model, but I need to order hardware.

**Comment by M66B** [comment]
@RobTillaart I don't think it will work without command code, but I'll try tonight.

Via RS232 it works. I can share some Python for this.

If you contact me via here, we can discuss via email:

https://contact.faircode.eu/?product=other

**Comment by RobTillaart** [comment]
Just changing some command strings in a copy of this library should work (sort of).

Might write a first version of the lib tonight although I planned to add two multiplexer classes first. 
I might need them in a project so they have priority.

Just ordered my MTP40F (and some more) at tinytronics.nl, hope to find time later this week "to play".

**Comment by M66B** [comment]
This is very basic, but it works:

https://gist.github.com/M66B/863b2ab8f36c51b2443e9db860c15a72

I switched to a Wemos D1 mini V4 in the meantime.

PXL_20230724_140628910

This is a work in progress:

https://gist.github.com/M66B/7cd4a04ff86ca16f9ccf09224ef26527

You can see what I've tried with I2C and the MTP40-F as well.

**Comment by M66B** [comment]
A disadvantage of the MTP40-F is that the maximum value is 2000 ppm. This can easily be reached in a room with many persons.

**Comment by M66B** [comment]
@RobTillaart without command code, the gas concentration / valid indication seems to be received via I2C. It is getting out of sync, though. With another command code than 0x03 (=read gas concentration) all zeroes are being received.

```
Wire.beginTransmission(address);
// No command code
if (Wire.endTransmission() != 0) return 0;
if (Wire.requestFrom(address, 3) == 3)
```

**Comment by RobTillaart** [comment]
Thanks for this info, helps to prep examples for the mtp40f library.
Yesterday I compared datasheets and the Serial commands and answers are definitely different.
Also did a small test to replace the (fast) CRC algorithm with a much smaller function to save RAM.
To be continued

**Comment by M66B** [comment]
I've just rewired to use RX/TX instead of I2C because it looks like I2C can be used to read value only, and not to calibrate, etc. I was looking into converting the Python code into cpp just now ...

**Comment by RobTillaart** [comment]
Created a placeholder for the MTP40F library - https://github.com/RobTillaart/MTP40F

No hardware in yet, but I try to prepare code as much as possible, including build-CI and examples.
When I get the hardware I can patch the code where needed.

The library is based on MTP40C library, some parts of the interface are different or not available.
First task now is to get all examples compiling on the MTP40F interface. 

I propose to open new issues at the new MTP40F repo.

**Comment by M66B** [comment]
I had no success in communication via RX/TX (which I had wired to MISO/MOSI). So, I rewired to I2C too.

**Comment by RobTillaart** [comment]
https://github.com/RobTillaart/MTP40F/pull/1  build is successful
- develop branch is "stable" as all examples compile.
- unit test is limited, however as far as testable no errors.
- LINT fails as library is not registered at Arduino libs yet.
- test if the lib works as intended can be done when hardware arrives.

**Comment by M66B** [comment]
I tried again with pin D0/D5, taking care of what is RX and TX, and there was still no response.
To be sure, I also tried one of the MZH19 libraries, and still nothing :-(
I guess I'm just stupid.

**Comment by RobTillaart** [comment]
Getting new hardware to work without problems takes time. I got my sensor and I will start testing this week. So if things go well the library could be working this weekend.

**Comment by RobTillaart** [comment]
FYI, I tested the CRC to use less RAM - https://github.com/RobTillaart/MTP40C/issues/9 - worked!

**Comment by RobTillaart** [comment]
> I tried again with pin D0/D5, taking care of what is RX and TX, and there was still no response. To be sure, I also tried one of the MZH19 libraries, and still nothing :-( I guess I'm just stupid.

First tests with the library shows nothing but an error 2.

**Comment by RobTillaart** [comment]
I2C tested, first I got nothing. but with this code it works - Note the Wire.write(0x03) !!
```cpp
uint16_t readMTP40F(int address)
{
  Wire.beginTransmission(address);
  Wire.write(0x03);
  if (Wire.endTransmission() != 0) return 0;

  if (Wire.requestFrom(address, 3) == 3)
  {
    uint16_t ppm = Wire.read() * 256;
    ppm += Wire.read();
    uint8_t status = Wire.read();
    if (status == 0xFF) Serial.print(" - error - ");
    return ppm;
  }
  return 0;
}
```

==>

```
PPM: 684
PPM: 684
PPM: 686
PPM: 693
PPM: 2000
PPM: 2000
PPM: 2000
PPM: 2000
PPM: 2000
PPM: 2000
PPM: 1533
PPM: 1549
PPM: 1567
PPM: 1645
PPM: 1646
PPM: 1641
PPM: 1632
PPM: 1575
PPM: 1557
PPM: 1429
PPM: 1177
PPM: 1164
PPM: 1152
PPM: 1104
PPM: 1093
PPM: 1082
PPM: 888
PPM: 864
PPM: 873
PPM: 873
PPM: 871
PPM: 869
PPM: 867
PPM: 865
PPM: 863
PPM: 860
PPM: 857
```

**Comment by M66B** [comment]
I have this working for some days already, but what isn't possible and disturbing, is that it isn't possible to calibrate, etc. via I2C.

**Comment by RobTillaart** [comment]
image

plotter.

**Comment by RobTillaart** [comment]
> I have this working for some days already, but what isn't possible and disturbing, is that it isn't possible to calibrate, etc. via I2C.

yep, but at least got some information out of it, so I know my sensor works 
(at least partially).

to be continued later this week.

**Comment by RobTillaart** [comment]
last hunch got serial working (sort of)

```
...Arduino\libraries\MTP40F\examples\MTP40F_getCO2_SW_SERIAL\MTP40F_getCO2_SW_SERIAL.ino
MTP40F_LIB_VERSION:	0.1.0

TIME	CO2 LEVEL
5000	XX: 915
10000	XX: 913
15000	XX: 909
20000	XX: 904
25000	XX: 865
30000	XX: 863
35000	XX: 860
40000	XX: 861
45000	XX: 934
50000	XX: 1657

```

I have to carefully analyze what I changed ...

**Comment by M66B** [comment]
Can you please share the source code? And also how you connected the sensor?

**Comment by RobTillaart** [comment]
I need to clean code up today, what I did was remove the CRC algorithm and add hardcoded CRC values.
So at least in that corner there is a BUG in that area.

Think I have fixed the CRC.
```
D:\Rob\WORK\Arduino\libraries\MTP40F\examples\MTP40F_getPressureReference\MTP40F_getPressureReference.ino
MTP40F_LIB_VERSION:	0.1.0

TIME	PRESSURE (mbar)
5000	1013
10000	1013
15000	1013
```

will push code to develop soon, but further testing is needed

**Comment by RobTillaart** [comment]
Pushed code to develop branch.
not all functionality is tested  - only getCO2 en get/set air pressure reference.
Other functions might need some patching in "data reconstruction"

I have other tasks now, to be continued later.

**Comment by RobTillaart** [comment]
Tested most of the examples, looks like the library now works correctly.
Will merge asap.

**Comment by M66B** [comment]
That's nice to hear. Can you please tell how you connected the sensor?

**Comment by RobTillaart** [comment]
Merged develop into master.
Build a first release asap

**Comment by RobTillaart** [comment]
> That's nice to hear. Can you please tell how you connected the sensor?


```
              UNO                     MTP40F
        +---------------+        +---------------+
        |               |        |               |
        |          +5V  |--------| 1 VIN         |
        |          GND  |--------| 2 GND         |
        |               |        | 3             |
        |               |        | 4             |
        |               |        |               |
        |               |        | 5             |
        |         RX 6  |--------| 6 TX          |
        |         TX 7  |--------| 7 RX          |
        |               |        | 8             |
        |               |        | 9             |
        |               |        |               |
        +---------------+        +---------------+

  use SoftwareSerial sws(7,6);
```

**Comment by RobTillaart** [comment]
@M66B 
Created - https://github.com/RobTillaart/MTP40F/issues/2
to discuss the new library as it does not belong here.

**Pull request merged**
